### ISSUE TITLE
Matcha & 0x Aggregator Trades overcounted in dex.trades

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/abstractions#610]
Here is a [query](https://dune.xyz/queries/281859) corresponding to [this transaction](https://etherscan.io/tx/0x040efe030d11cc13146b5b078cf9c8166b7084b3e40b94bbc2a837237b48816f) demonstrating that a "single" token swap is being counted 6x in the `dex.trades` table.

1. There is double accounting for the same aggregator (0x and Matcha)
2. Each of the 3 "hops" of the trade is being counted on both aggregators.

Realistically, it makes sense to count each of the DEX trades, but for an aggregator protocol, this should only be counted a single trade for the user `0xd3f8f55b6b244afd86f2d0fb7f2de445cc0c10a8` who swapped ICE for USDC.

Or, at the very least only counted as a single aggregator (not two).

**Comment by masquot** [comment]
Thank you @bh2smith. Adding @sui414 to this discussion.

**Comment by sui414** [comment]
hey @bh2smith thanks for the comments. 0x API and Matcha are not the same aggregators. 0x API is an infra layer providing endpoints for different integrators including Matcha, Zerion, Zapper, Metamask, CowSwap and many more to use the `/swap` functionality. Which means e.g. you can find also same trades being recorded under Metamask **and** 0x API. 

Essentially, right now 1inch, 0x API and Paraswap are the 3 aggregators that are providing this infra for other dapps, which means the others like Metamask who compares 3 services for best price are "aggregators of aggregators". That's why when we compare[ agg market share](https://dune.xyz/danning.sui/dex-aggregators-by-sui414), we only include these 3.

In terms of 3hops, why it makes more sense counting single leg when it's aggregators but multi legs when it's DEX? i dont understand.

**Comment by bh2smith** [comment]
Hey there @sui414 and thanks for your response. I am not necessarily interested in counting the transaction hash, but more concerned about the unfairness in overall trading volume accounting. Let me elaborate:

I can understand that Matcha and 0x are different - but the fact that they are attributing each hop of the trade towards their trading volume is unfair to the other aggregators who do not record their volume this way. A user comes to their platform and gets a quote for a trade (token A for token B). The aggregator facilitates this trade via multiple hops through other dexes, but in all fairness they should record the volume of the trade. Observe example transactions of all the other aggregators facilitating multi-hop trades through other dexes.

Gnosis Protocol (OHM->DAI->USDT->WETH)
    https://dune.xyz/queries/284859

Paraswap (YFI->WETH->UNI)
    https://dune.xyz/queries/284853

1Inch (USDT->WETH->GALA)
    https://dune.xyz/queries/284841

Its a bit late for me now, but I can fill in a few more details tomorrow if this is unclear.

**Comment by fleupold** [comment]
Related twitter discussion on this topic: https://twitter.com/koeppelmann/status/1468182447892348928

> I think these 2 methodology are generally measuring 2 aspects

@sui414 I totally agree! But I also agree with @bh2smith that it would be great to get the `dex.trades` table report the same metric for all aggregators in order to allow easy comparison between them (right now it looks like Match is way ahead of Paraswap, whereas in reality they aren't if the same metric was used).

![image](https://user-images.githubusercontent.com/1200333/145399181-bf6176e3-8ba5-4183-bd8a-98ebad2a387a.png)

**Comment by bh2smith** [comment]
Here is an example of a trade (~1.6M USDC-> WETH) on Gnosis Protocol that was routed through the 0x API. It is reported at 1.6M USD trade on Gnosis Protocol but 3.2M USD on 0x.

https://dune.xyz/queries/286323?txHash=0x5a28ad6b02bd66c94002064ff911a026e22e83b4583964736fb68a7cc351b25b

<img width="896" alt="Screenshot 2021-12-09 at 1 54 34 PM" src="https://user-images.githubusercontent.com/11778116/145400198-01985b3e-d605-49f7-aa1e-740129e273a8.png">


Note that I have uncovered the fact that not all 0x/Matcha transactions are incorrectly reporting in this way. Specifically when the sell volume is "split" over multiple AMMs, these trade values add up to the correct amount. Its only for multi-hop routing that the over counting occurs.

The way that the other aggregators are able to evaluate these trading volumes consistently as "trades" is usually by using the "Trade" event emitted by the contract. I will have to do a bit more research on the 0x contracts to determine if such events are available, but what I imagine is happening here is that the entries are built by accrediting all "Transfer" events as swaps. From the code here https://github.com/duneanalytics/abstractions/blob/master/ethereum/dex/trades/insert_zeroex.sql it seems that some contract events are being used to populate the table, but I am not overly familiar with them at this time to propose a suggestion.

**Comment by sui414** [comment]
thank you both for the comments & elaboration🙏 . currently at team offsite so might have delay respond until mid next week.

one thing to note tho - 0x has both **aggregator** portion (labeled as "0x API") and **DEX** portion (labeled "0x Native", rfq & open orders i.e. limit orders) - the DEX portion is where we see overlap with paraswap above and is **not** included in that dash. for that dash, we only count "0x API" /swap endpoint volume. (limit order volume is thru another endpoint `orderbook`).

appreciate your research in depth on this! we currently don't log multi-hop events and might need to decode from traces, or do extra clean up on those trades -- if we agree to dedup on those cases.

why wouldn't we necessarily think multi-legs on multi-hop should be all counted? by all aggregators? it does 
1: accrue fees; 
2: have counterparties if we count LPs.

**Comment by fleupold** [comment]
> why wouldn't we necessarily think multi-legs on multi-hop should be all counted? by all aggregators?

My feeling is that aggregators primarily serve users (not liquidity providers) and should therefore report volume based on the user intent (Swap A for B regardless of whether it goes through C). Otherwise an aggregator who is serving the user better (e.g. not using a longer route if the trade execution cost is not worth the price improvement, or matching against a direct market maker) may be represented as worse (they used less hops) when looking at the top line metric.

For Meta DEX Aggregators like CowSwap counting the sum of all hops would also raise the question if we should then count the 0x Volume + underlying AMM volume together (seems silly)? For CowSwap in particular it is better to use less AMMs as this means less potential for MEV (similar to 0x RFQ orders).

**Comment by bh2smith** [comment]
It appears we have not come to consensus here and that things will remain as they are. Each party has valid arguments for both forms of accounting.
